name: ChestFinder
main: me.lasillje.chestfinder.ChestFinder
version: 1.0
api-version: 1.13
commands:
   findchest:
      description: Base command for ChestFinder.
      usage: /<command> [<radius>] [list] [open <index>]
